spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${PGPASSWORD}
    password: ${PGUSER}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true