spring:
  secret: ${SECRET:NO_SECRET}
  profiles:
    active: ${ENVIRONMENT:local}
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    generate-ddl: true
  flyway:
#    enabled: false
    enabled: true
    validate-on-migrate: true
  cors:
    mode: default