spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/norgestur-db
    username: postgres
    password: entur123
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
    url: jdbc:postgresql://localhost:5432/norgestur-db
    user: postgres
    password: entur123
    clean-on-validation-error: true
    clean-disabled: false