spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/norgestur-db
    username: postgres
    password: entur123
  jpa:
    show-sql: true
  flyway:
    # TODO: remove this before deployment
    enabled: true
   # validate-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false