spring:
  profiles:
    active: ${ENVIRONMENT:local}
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true