common:
  env: tst
  ingress:
    host:
      entur-game-backend.staging.entur.io
  container:
    cpu: 1
    memory: 300
    replicas: 2
    maxReplicas: 2
  configmap:
    enabled: true
    toEnv: true
    data:
      ENVIRONMENT: staging
      TZx: "Europe/Oslo"
      permission_url: "http://permission-store.tst.entur.internal"
      entur.auth.external.resource: "file:/config/staging/providers.properties"
      DATABASE_URL: jdbc:postgresql://localhost:5432/tst_game-backend
      oauth_client_domain: internal.staging.entur.org
      oauth_client_audiences: https://api.staging.entur.io
  postgres:
    cpu: 1
    memory: 64
