common:
  env: prd
  ingress:
    host:
      entur-game-backend.entur.io
  container:
    cpu: 1
    memory: 300
    replicas: 2
    maxReplicas: 3
  configmap:
    enabled: true
    toEnv: true
    data:
      ENVIRONMENT: production
      TZx: "Europe/Oslo"
      permission_url: "http://permission-store.prd.entur.internal"
      entur.auth.external.resource: "file:/config/production/providers.properties"
      db_url: jdbc:postgresql://localhost:5432/prd_game-backend
      oauth_client_domain: internal.entur.org
      oauth_client_audiences: https://api.entur.io
  postgres:
    cpu: 1
    memory: 64
