common:
  app: entur-game-backend
  shortname: enturbckend
  team: portal
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 8080
  container:
    cpu: 0.3
    memory: 128
    cpuLimit: 1.0
    replicas: 1
    image: <+artifacts.primary.image>
    probes:
      liveness:
        path: "/actuator/health"
      readiness:
        path: "/actuator/health"
  postgres:
    enabled: true
    cpu: 0.3
    cpuLimit: 1.0
    memory: 64
  configmap:
    enabled: true
    toEnv: true
    data:
      TZx: "Europe/Oslo"
