name: build and push

on:
  push:
    branches:
      - main

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Build with Gradle
        run: ./gradlew --no-daemon clean build
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_APIKEY: ${{ secrets.ARTIFACTORY_APIKEY }}
      - name: Archive Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/libs
          retention-days: 1
          overwrite: true

  docker-build:
    needs: gradle-build
    uses: entur/gha-docker/.github/workflows/build.yml@v1.3.3
    with:
      build_artifact_name: app
      build_artifact_path: build/libs

  docker-push:
    needs: docker-build
    uses: entur/gha-docker/.github/workflows/push.yml@v1.3.3